# Generated by Django 6.0.2 on 2026-02-12 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestQRRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=150)),
                ('guest_surname', models.CharField(max_length=150)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(blank=True, default='', max_length=20)),
                ('remark', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('novus_user_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('novus_card_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('novus_credential_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('qr_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_qr_requests', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guest QR Request',
                'verbose_name_plural': 'Guest QR Requests',
                'db_table': 'qr_requests_guestqrrequest',
                'ordering': ['-created_at'],
            },
        ),
    ]
